### ISSUE TITLE
Where a can buy

### ISSUE THREAD

**Issue by VictorSalton** [Linlijian/PikunBot-Mir4#5]
how can i contact the developer, i'm interested in buying

**Comment by damnyou01** [comment]
> how can i contact the developer, i'm interested in buying

DM me ican give u some

**Comment by charlylei12** [comment]
> > how can i contact the developer, i'm interested in buying
> 
> DM me ican give u some

hi do you still have the latest mir4 bot until now? can you also share it with me sir if its ok with you?
